on:
  pull_request:
    branches:
      - release
    types: [closed]

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - if: github.event.pull_request.merged == true
        name: Run
        run: |
          echo  "pull request merged "
          echo "${{ commits[0][message] }}"
