on:
  pull_request:
    branches:
      - release

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - name: Post multi-line comments
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        URL: ${{ github.event.pull_request.comments_url }}
      run: |
       cat ${GITHUB_EVENT_PATH}
