on:
  push:
  pull_request:
    types:
    - assigned
    - unassigned
    - labeled
    - unlabeled
    - opened
    - edited
    - closed
    - reopened
    - synchronize
    - converted_to_draft
    - ready_for_review
    - locked
    - unlocked
    - review_requested
    - review_request_removed
    - auto_merge_enabled
    - auto_merge_disabled
    branches:
      - release

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - name: Post multi-line comments
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        URL: ${{ github.event.pull_request.comments_url }}
      run: |
       cat ${GITHUB_EVENT_PATH}
       echo type: ${{ github.event.pull_request.types }}
